repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
            exclude: /templates
        -   id: trailing-whitespace
        -   id: mixed-line-ending
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.31.0
        hooks:
        -   id: pyupgrade
            args: [--py38-plus]
    -   repo: https://github.com/adamchainz/django-upgrade
        rev: 1.4.0
        hooks:
        -   id: django-upgrade
            args: [--target-version, "2.2"]
    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.9.0
        hooks:
        -   id: python-check-mock-methods
        -   id: python-no-eval
        -   id: python-no-log-warn
    -   repo: https://github.com/pycqa/flake8
        rev: 4.0.1
        hooks:
        -   id: flake8
            args:
                - "--max-line-length=120"
            exclude: migrations/
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-simplify
    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        -   id: isort
            name: isort (python)
            exclude: migrations/
