# Generated by Django 3.2.15 on 2022-08-13 14:09

from django.db import migrations, models
import django.db.models.deletion
import file_field_utils.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tips', models.TextField(blank=True, default='')),
                ('image', file_field_utils.db.fields.SVGAndImageField(blank=True, upload_to='exercises/')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', file_field_utils.db.fields.SVGAndImageField(blank=True, upload_to='weeks/')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=128)),
                ('image', file_field_utils.db.fields.SVGAndImageField(blank=True, upload_to='trainings/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Training duration in seconds')),
                ('repetitions_number', models.PositiveSmallIntegerField(default=1)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='app.week')),
            ],
            options={
                'ordering': ('week', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Exercise duration in seconds')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.exercisetype')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='app.training')),
            ],
        ),
    ]
