version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=runners_app
    ports:
      - "5432:5432"
    expose:
      - 5432
  web:
    build:
      context: ..
      dockerfile: ".build/Dockerfile.prod"
    command: gunicorn runnersApp.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    links:
      - db
    depends_on:
      - db

volumes:
  postgres_data:
